# Generated by Django 5.1.5 on 2025-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='confirm_password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
