# Generated by Django 5.1.5 on 2025-03-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_worker_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='confirm_password',
        ),
    ]
