# Generated by Django 5.1.5 on 2025-02-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_worker_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Ms', 'Ms.')], default='Mr', max_length=10),
        ),
    ]
