# Generated by Django 5.1.5 on 2025-03-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_worker_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
