# Generated by Django 5.1.5 on 2025-02-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_worker_email_alter_worker_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='skills',
            new_name='profession',
        ),
    ]
