# Generated by Django 5.1.5 on 2025-02-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default='Not provided', max_length=100),
        ),
    ]
