# Generated by Django 5.1.5 on 2025-03-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_user_address_alter_user_city_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='experience',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
