# Generated by Django 5.1.5 on 2025-03-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_notification_is_read_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('complete', 'Complete'), ('request', 'Request')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
