# Generated by Django 5.1.5 on 2025-03-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.worker')),
            ],
        ),
    ]
