# Generated by Django 5.1.5 on 2025-03-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_request_worker_alter_worker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
