# Generated by Django 5.1.5 on 2025-03-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_request_worker_alter_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
