# Generated by Django 5.1.5 on 2025-03-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_worker_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='is_approved',
        ),
    ]
