# Generated by Django 5.1.5 on 2025-03-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_worker_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
